### ISSUE TITLE
issue in logout page

### ISSUE THREAD

**Issue by suriyaprakash-25** [suriyaprakash-25/CODEHOLICS#1]
the logout page is not working in the correct way..we should see to it

**Comment by yugen847** [comment]
![Screenshot 2024-12-26 100458](https://github.com/user-attachments/assets/22e0612f-aede-465b-bf0f-a739c98b68c0)


the issue is corrrected...that was a silly mistake that its javascript file was not linked with it..now its done...thank you surya for pointing out this issue.
